development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:4010d7cae0946d8bcbc5ca2a2bfbff8c@spinyfin.redistogo.com:9396
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

  # inline: true
  # # redis://localhost:6379/1
  # password: 

development:
  adapter: async

test:
  adapter: async

  channel_prefix: lucky_bidwell_backend_production
